// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMnBUJIHt1OfNUHkrqnnFkIu0JsZPiLAM',
    appId: '1:671101750738:android:b02c9cb5a465f450b8cc0b',
    messagingSenderId: '671101750738',
    projectId: 'emotiflow-b1ef1',
    storageBucket: 'emotiflow-b1ef1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyDpfunHvYCzj8T7IjWXsv1x5kymQBTPbDY', // iOS 정보는 추측값이니 나중에 확인 필요
    appId: '1:671101750738:ios:5a33c0e444adf1a4b8cc0b',
    messagingSenderId: '671101750738',
    projectId: 'emotiflow-b1ef1',
    storageBucket: 'emotiflow-b1ef1.firebasestorage.app',
  );
}
